config/routes.rb
Rails.application.routes.draw do
  resources :clients

   root 'clients#index'

end

app/models/client.rb
class Client < ActiveRecord::Base
	mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def hello
    render text: "hola, mundo!"
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:name, :email, :phone, :age, :date_of_birth, :image)

    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <%= form_for @client, html: {:multipart => true} do |f| %>
        <% if @client.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h2>

            <ul>
            <% @client.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="field">
          <%= f.label :nombre %><br>
          <%= f.text_field :name %>
        </div>
        <div class="field">
          <%= f.label :correo_electrónico %><br>
          <%= f.text_field :email %>
        </div>
        <div class="field">
          <%= f.label :teléfono %><br>
          <%= f.text_field :phone %>
        </div>
        <div class="field">
          <%= f.label :edad %><br>
          <%= f.number_field :age %>
        </div>
        <div class="field">
          <%= f.label :fecha_de_nacimiento %><br>
          <%= f.date_select :date_of_birth, :start_year=>1900,:end_year=>2016 %>
        </div>
        <div class="field">
          <%= f.label :sube_tu_avatar %><br>
          <%= f.file_field :image %>
        </div>
        <div class="actions">
          <%= f.submit 'Crear Cliente',  :class => 'btn btn-catalogo'%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/clients/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<h1 class="titulo">Editar Información del Cliente</h1>

				<%= render 'form' %>
			</div>
	</div>
	<div class="row">
		<div class="col-md-6 col-md-offset-4">
			<br>
			<%= link_to 'Ver el cliente', @client %> |
				<%= link_to 'Regresar', clients_path %>
		</div>
	</div>
</div>

app/views/clients/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-4">
      <h1 class="titulo">Listado de Clientes</h1>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <table class="table table-hover table-bordered">
        <thead>
          <tr>

            <th>Nombre</th>
            <th>Correo Electrónico</th>
            <th>Teléfono</th>
            <th>Edad</th>
            <th>Fecha de Nacimiento</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @clients.each do |client| %>
            <tr>
              <td><%= client.name %></td>
              <td><%= client.email %></td>
              <td><%= client.phone %></td>
              <td><%= client.age %></td>
              <td><%= client.date_of_birth %></td>
              <td class="actions"><%= link_to 'Ver Cliente', client %></td>
              <td><%= link_to 'Editar ', edit_client_path(client) %></td>
              <td><%= link_to 'Eliminar', client, method: :delete, data: { confirm: '¿Estás seguro?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

  <div class="row">
    <div class="col-md-4 col-md-offset-5">
      <%= link_to 'Crear Nuevo Cliente', new_client_path, class: "btn btn-catalogo" %>
    </div>
  </div>
  <br>
</div>

app/views/clients/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<h1 class="titulo">Crear un Nuevo Cliente</h1>

				<%= render 'form' %>
			</div>
	</div>
	<div class="row">
		<div class="col-md-6 col-md-offset-4">
			<br>

			<%= link_to 'Regresar', clients_path %>
		</div>
	</div>
</div>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="row">
    <div class="col-md-2">
      <%= image_tag @client.image.thumb.url , class: "img-circle"%>
    </div>
    <div class="col-md-6">
      <p>
        <strong>Nombre:</strong>
        <%= @client.name %>
      </p>
      <p>
        <strong>Correo electrónico:</strong>
        <%= @client.email %>
      </p>

      <p>
        <strong>Teléfono:</strong>
        <%= @client.phone %>
      </p>

      <p>
        <strong>Edad:</strong>
        <%= @client.age %>
      </p>

      <p>
        <strong>Fecha de Nacimiento:</strong>
        <%= @client.date_of_birth %>
      </p>
    </div>
  </div>
  <div class="row">
    <div class="col-md-2">
      <%= link_to 'Editar', edit_client_path(@client) %> |
      <%= link_to 'Regresar', clients_path %>
    </div>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Catálogo de Clientes</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">
        <p>Catálogo de Clientes</p>
      </a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Clientes', clients_path %></li>
        <li><%= link_to 'Crear Nuevo Cliente', new_client_path %></li>
       
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>


<%= yield %>

<footer class="footer">
  <div class="col-md-12 centered">
    <p class="pull-left">Por Andrea Dardón - <a href="mailto:amdardon@gmail.com">amdardon@gmail.com</a></p>
  </div>
</footer>

</body>
</html>